# Generated by Django 4.0.5 on 2022-08-16 15:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribersDesiresMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD_Desire_first', models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)  جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني  (06)'), ('03-March______راجب-(07)           ', '03-March        رجب           (07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان         (08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان         (09)'), ('06-June_______شوال-(10)           ', '06-June         شوال          (10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة     (11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة      (12)'), ('09-September__محرم-(01)           ', '09-September    محرم          (01)'), ('10-October____صفر-(02)            ', '10-October      صفر           (02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول    (03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني   (04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الأولى')),
                ('SD_Desire_second', models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)  جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني  (06)'), ('03-March______راجب-(07)           ', '03-March        رجب           (07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان         (08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان         (09)'), ('06-June_______شوال-(10)           ', '06-June         شوال          (10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة     (11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة      (12)'), ('09-September__محرم-(01)           ', '09-September    محرم          (01)'), ('10-October____صفر-(02)            ', '10-October      صفر           (02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول    (03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني   (04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الثانية')),
                ('SD_Desire_third', models.CharField(choices=[('01-January____جمادى الأولى-(05)   ', '01-January      (05)  جمادى الأولى'), ('02-February___جمادى الثاني-(06)   ', '02-February     جمادى الثاني  (06)'), ('03-March______راجب-(07)           ', '03-March        رجب           (07)'), ('04-April______شعبان-(08)          ', '04-April        شعبان         (08)'), ('05-May________رمضان-(09)          ', '05-May          رمضان         (09)'), ('06-June_______شوال-(10)           ', '06-June         شوال          (10)'), ('07-July_______ذو القعدة-(11)      ', '07-July         ذو القعدة     (11)'), ('08-August_____ذو الحجة-(12)       ', '08-August       ذو الحجة      (12)'), ('09-September__محرم-(01)           ', '09-September    محرم          (01)'), ('10-October____صفر-(02)            ', '10-October      صفر           (02)'), ('11-November___ربيع الأول-(03)     ', '11-November     ربيع الأول    (03)'), ('12-December___ربيع الثاني-(04)    ', '12-December     ربيع الثاني   (04)'), ('لم يتم تحديد اي رغبة حتى الأن-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='لم يتم تحديد اي رغبة حتى الأن-(00)', help_text='Required Field', max_length=50, verbose_name='الرغبة الثالثة')),
                ('SD_Notes', models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات')),
                ('SD_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'verbose_name_plural': 'Subscribers Desires',
            },
        ),
        migrations.CreateModel(
            name='PersonalsMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='الإسم التعريفي')),
                ('P_FirstName', models.CharField(db_index=True, max_length=50, verbose_name='الإسم الأول')),
                ('P_FatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الاب')),
                ('P_GrandFatherName', models.CharField(db_index=True, max_length=50, verbose_name='إسم الجد')),
                ('P_FamilyName', models.CharField(db_index=True, max_length=50, verbose_name='إسم العائلة')),
                ('P_Photo', models.ImageField(db_index=True, default='Default_Image.png', upload_to='PersonaFile_Photo/', verbose_name='الصورة الشخصية')),
                ('P_Mobile', phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='+966555555555', max_length=128, region=None, verbose_name='الجوال')),
                ('P_Address', models.CharField(db_index=True, max_length=100, verbose_name='العنوان')),
                ('P_Notes', models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات')),
                ('P_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementsMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FS_SubscriptionAmount', models.DecimalField(db_index=True, decimal_places=2, default=50, max_digits=8, verbose_name='مبلغ الإشتراك')),
                ('FS_NumberPaymentsDue', models.IntegerField(db_index=True, default=1, verbose_name='عدد الدفعات')),
                ('FS_BankName', models.CharField(db_index=True, max_length=50, verbose_name='إسم البنك')),
                ('FS_BankAccount', models.CharField(db_index=True, max_length=50, verbose_name='الحساب البنكي - الآيبان')),
                ('FS_Notes', models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات')),
                ('FS_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'verbose_name_plural': 'Financial Statements',
            },
        ),
        migrations.CreateModel(
            name='DatesReceivingMoneyPaymentsMODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRMP_DateReceivingMoneyPayments_Long', models.CharField(choices=[('01-January__Jumada Al-Awwal-(05)  ', '01-January      (05)  جمادى الأولى'), ('02-February_Jumada Al-Thani-(06)  ', '02-February     جمادى الثاني  (06)'), ('03-March______________Rajab-(07)  ', '03-March        رجب           (07)'), ('04-April_____________Shaban-(08)  ', '04-April        شعبان         (08)'), ('05-May______________Ramadan-(09)  ', '05-May          رمضان         (09)'), ('06-June_____________Shawwal-(10)  ', '06-June         شوال          (10)'), ('07-July__________Dhul-Qadah-(11)  ', '07-July         ذو القعدة     (11)'), ('08-August_______Dhul-Hijjah-(12)  ', '08-August       ذو الحجة      (12)'), ('09-September_______Muharram-(01)  ', '09-September    محرم          (01)'), ('10-October____________Safar-(02)  ', '10-October      صفر           (02)'), ('11-November___Rabi Al-Awwal-(03)  ', '11-November     ربيع الأول    (03)'), ('12-December___Rabi Al-Thani-(04)  ', '12-December     ربيع الثاني   (04)'), ('The Date Has Not Yet Been Set-(00)', 'لم يتم تحديد اي رغبة حتى الأن-(00)')], db_index=True, default='The Date Has Not Yet Been Set-(00)', help_text='Required Field', max_length=50, verbose_name='موعد إستلام المال - بالشهر')),
                ('DRMP_DateReceivingMoneyPayments_Short', models.DateField(blank=True, db_index=True, default=datetime.date.today, help_text='Required Field', null=True, verbose_name='موعد إستلام المال - بالتاريخ')),
                ('DRMP_Notes', models.CharField(blank=True, db_index=True, default='-', max_length=100, null=True, verbose_name='الملاحظات')),
                ('DRMP_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اسم المشترك')),
            ],
            options={
                'verbose_name_plural': 'Dates Receiving Money Payments',
            },
        ),
    ]
